substitutions:
  _IMAGE_NAME: hello-nodejs # Your name image
  _GCS_CACHE_BUCKET: cloud-build-maven-cache # Your bucket
  _SERVICE_NAME: hello-nodejs-srv # Your Cloud Run service name 
  _REGION: asia-southeast1 # Your region
  _GCR_HOST: asia.gcr.io # Your GCR Host

steps:
 
# Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOST/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build

# Push Docker image to Google Container Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOST/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA'
    id: Push
    
# Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', '${_SERVICE_NAME}', '--image', '$_GCR_HOST/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA', '--region', '${_REGION}' ]
    id: Deploy
